VAR pokemon_name = ""
VAR CurrentItem = ""
VAR tradingItem1 = "<color=\green>Yoshi Doll</color>"
VAR tradingItem2 = "<color=\red>Ribbion</color>"
VAR tradingItem3 = "Dog Food"
VAR tradingItem4 = "Bananas"
VAR tradingItem5 = "Stick"

VAR ItemSlot0 = "flash light"
VAR ItemSlot1 = "candy bar"
VAR ItemSlot2 = ""
VAR ItemSlot3 = ""
VAR ItemSlot4 = ""
VAR ItemSlot5 = ""
VAR ItemSlot6 = ""
VAR ItemSlot7 = ""
VAR ItemSlot8 = ""